#define	LSOF_BLDCMT	""
#define	LSOF_CC		"x86_64-linux-android-clang -fPIE -fPIC --sysroot=/opt/toolchain/android-toolchain-x86_64-4.9-android-24_r17/sysroot -I/home/itri-android/cba/htop-android/../lxc/android-libs/x86_64/include -pie -L/home/itri-android/cba/htop-android/../lxc/android-libs/x86_64/lib "
#define	LSOF_CCV	""
#define	LSOF_CCDATE	"Fri Apr 27 00:01:31 CST 2018"
#define	LSOF_CCFLAGS	"-O -DHAS_STRFTIME -DHASNORPC_H -DGLIBCV -DLINUXV=44117 -DHASIPv6 -DNEEDS_NETINET_TCPH -DHASSELINUX -DHASUXSOCKEPT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DLSOF_VSTR=\"4.4.117\" -O"
#define	LSOF_CINFO	""
#define	LSOF_HOST	"x86_64-linux-android"
#define	LSOF_LDFLAGS	"-L./lib -llsof  -lselinux"
#define	LSOF_LOGNAME	"itri-android"
#define	LSOF_SYSINFO	"Linux mitlabserver-X10DAi 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux"
#define	LSOF_USER	"itri-android"
#define	LSOF_VERSION	"4.89"
